const moonData = [
  {
    id: "lune",
    englishName: "Moon",
    nameDetail:
      'The usual English proper name for Earth\'s natural satellite is simply Moon, with a capital M. The noun moon is derived from Old English mōna, which (like all its Germanic cognates) stems from Proto-Germanic *mēnōn, which in turn comes from Proto-Indo-European *mēnsis "month" (from earlier *mēnōt, genitive *mēneses) which may be related to the verb "measure" (of time). Occasionally, the name Luna /ˈluːnə/ is used in scientific writing[23] and especially in science fiction to distinguish the Earth\'s moon from others, while in poetry "Luna" has been used to denote personification of the Moon. Cynthia /ˈsɪnθiə/ is another poetic name, though rare, for the Moon personified as a goddess, while Selene /səˈliːniː/ (literally "Moon") is the Greek goddess of the Moon.',
    perihelion: 363300,
    aphelion: 405500,
    inclination: 5.145,
    massValue: 7.346,
    massExponent: 22,
    gravity: 1.62,
    meanRadius: 1737.0,
    sideralOrbit: 27.3217,
    sideralRotation: 655.728,
    planet: "terre",
    discoveredBy: "",
    discoveryDate: "",
    bodyType: "Moon",
  },
  {
    id: "phobos",
    englishName: "Phobos",
    nameDetail:
      "Named after Phobos, the Greek god of fear and panic, who is the son of Ares (Mars) and twin brother of Deimos.",
    perihelion: 9234,
    aphelion: 9518,
    inclination: 1.075,
    massValue: 1.06,
    massExponent: 16,
    gravity: 0.0057,
    meanRadius: 11.1,
    sideralOrbit: 0.31891,
    sideralRotation: 0.7653,
    planet: "mars",
    discoveredBy: "Asaph Hall",
    discoveryDate: "12/08/1877",
    bodyType: "Moon",
  },
  {
    id: "deimos",
    englishName: "Deimos",
    nameDetail:
      "Named after Deimos, the Ancient Greek god and personification of dread and terror.",
    perihelion: 23456,
    aphelion: 23471,
    inclination: 1.075,
    massValue: 1.4762,
    massExponent: 15,
    gravity: 0.003,
    meanRadius: 6.2,
    sideralOrbit: 1.26244,
    sideralRotation: 30.29856,
    planet: "mars",
    discoveredBy: "Asaph Hall",
    discoveryDate: "12/08/1877",
    bodyType: "Moon",
  },
  {
    id: "io",
    englishName: "Io",
    nameDetail:
      "Named after the mythological character Io, a priestess of Hera who became one of Zeus's lovers.",
    perihelion: 420071,
    aphelion: 423529,
    inclination: 0.036,
    massValue: 8.932,
    massExponent: 22,
    gravity: 1.79,
    meanRadius: 1821.5,
    sideralOrbit: 1.76914,
    sideralRotation: 42.4593,
    planet: "jupiter",
    discoveredBy: "Galileo Galilei",
    discoveryDate: "07/01/1610",
    bodyType: "Moon",
  },
  {
    id: "europe",
    englishName: "Europa",
    nameDetail:
      "Named after Europa, the Phoenician mother of King Minos of Crete and lover of Zeus.",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.466,
    massValue: 4.8,
    massExponent: 22,
    gravity: 1.31,
    meanRadius: 1560.8,
    sideralOrbit: 3.55118,
    sideralRotation: 85.2293,
    planet: "jupiter",
    discoveredBy: "Galileo Galilei",
    discoveryDate: "08/01/1610",
    bodyType: "Moon",
  },
  {
    id: "ganymede",
    englishName: "Ganymede",
    nameDetail:
      "Ganymede is the only Galilean moon of Jupiter named after a male figure—like Io, Europa, and Callisto, he was a lover of Zeus.",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.177,
    massValue: 1.4819,
    massExponent: 23,
    gravity: 1.428,
    meanRadius: 2631.2,
    sideralOrbit: 7.15455,
    sideralRotation: 171.7093,
    planet: "jupiter",
    discoveredBy: "Galileo Galilei",
    discoveryDate: "11/01/1610",
    bodyType: "Moon",
  },
  {
    id: "callisto",
    englishName: "Callisto",
    nameDetail:
      "Callisto is named after one of Zeus's many lovers or other sexual partners in Greek mythology. Callisto was a nymph (or, according to some sources, the daughter of Lycaon) who was associated with the goddess of the hunt, Artemis.",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.192,
    massValue: 1.0759,
    massExponent: 23,
    gravity: 1.235,
    meanRadius: 2410.3,
    sideralOrbit: 16.68902,
    sideralRotation: 400.536,
    planet: "jupiter",
    discoveredBy: "Galileo Galilei",
    discoveryDate: "07/01/1610",
    bodyType: "Moon",
  },
  {
    id: "amalthee",
    englishName: "Amalthea",
    nameDetail:
      "Named it after Amalthea (foster mother of Zeus) of Greek mythology.",
    perihelion: 181150,
    aphelion: 182840,
    inclination: 0.38,
    massValue: 7.5,
    massExponent: 18,
    gravity: 0.02,
    meanRadius: 84.0,
    sideralOrbit: 0.49818,
    sideralRotation: 11.9563,
    planet: "jupiter",
    discoveredBy: "E. Barnard",
    discoveryDate: "09/09/1892",
    bodyType: "Moon",
  },
  {
    id: "himalia",
    englishName: "Himalia",
    nameDetail:
      "Named after the nymph Himalia, who bore three sons of Zeus -Spartaeus, Kronios, and Kytos.",
    perihelion: 9782900,
    aphelion: 13082000,
    inclination: 27.5,
    massValue: 9.5,
    massExponent: 18,
    gravity: 0.062,
    meanRadius: 85.0,
    sideralOrbit: 250.5662,
    sideralRotation: 7.7808,
    planet: "jupiter",
    discoveredBy: "C. Perrine",
    discoveryDate: "03/12/1904",
    bodyType: "Moon",
  },
  {
    id: "elara",
    englishName: "Elara",
    nameDetail:
      "Named after Elara, one of Zeus's lovers and the mother of the giant Tityos.",
    perihelion: 0,
    aphelion: 0,
    inclination: 26.63,
    massValue: 8.0,
    massExponent: 17,
    gravity: 0.031,
    meanRadius: 40.0,
    sideralOrbit: 259.6528,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "C. Perrine",
    discoveryDate: "02/01/1905",
    bodyType: "Moon",
  },
  {
    id: "pasiphae",
    englishName: "Pasiphae",
    nameDetail:
      "Originally named Jupiter VIII, Pasiphaë offially named in 1975 after the mythological wife of Minos and mother of the Minotaur from Greek legend.",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.4,
    massValue: 3.0,
    massExponent: 17,
    gravity: 0.022,
    meanRadius: 18.0,
    sideralOrbit: 743.6,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "P. Melotte",
    discoveryDate: "27/01/1908",
    bodyType: "Moon",
  },
  {
    id: "sinope",
    englishName: "Sinope",
    nameDetail:
      "Originaly named Jupiter IX, Sinope was official named in 1975  after the figure of the same name from Greek mythology",
    perihelion: 0,
    aphelion: 0,
    inclination: 158.1,
    massValue: 8.0,
    massExponent: 16,
    gravity: 0.014,
    meanRadius: 14.0,
    sideralOrbit: 758.9,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Seth Barnes Nicholson",
    discoveryDate: "21/07/1914",
    bodyType: "Moon",
  },
  {
    id: "lysithea",
    englishName: "Lysithea",
    nameDetail:
      "Originally known as Jupiter X, Lysithea was officially named in 1975 after the mythological daughter of Oceanus and one of Zeus' lovers.",
    perihelion: 0,
    aphelion: 0,
    inclination: 28.3,
    massValue: 8.0,
    massExponent: 16,
    gravity: 0.013,
    meanRadius: 12.0,
    sideralOrbit: 259.22,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Seth Barnes Nicholson",
    discoveryDate: "06/07/1938",
    bodyType: "Moon",
  },
  {
    id: "carme",
    englishName: "Carme",
    nameDetail:
      "Not named until 1975, Carme is named after the mythological Carme, mother by Zeus of Britomartis, a Cretan goddess.",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.9,
    massValue: 1.0,
    massExponent: 17,
    gravity: 0.017,
    meanRadius: 15.0,
    sideralOrbit: 734.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Seth Barnes Nicholson",
    discoveryDate: "30/07/1938",
    bodyType: "Moon",
  },
  {
    id: "ananke",
    englishName: "Ananke",
    nameDetail:
      "Not named until 1975, Anake is named after the Greek mythological Ananke, the personification of necessity, and the mother of the Moirai (Fates) by Zeus. ",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.9,
    massValue: 4.0,
    massExponent: 16,
    gravity: 0.01,
    meanRadius: 10.0,
    sideralOrbit: 629.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Seth Barnes Nicholson",
    discoveryDate: "28/09/1951",
    bodyType: "Moon",
  },
  {
    id: "leda",
    englishName: "Leda",
    nameDetail:
      "Named after Leda, who was raped by Zeus, the Greek equivalent of Jupiter (who came to her in the form of a swan)",
    perihelion: 0,
    aphelion: 0,
    inclination: 27.46,
    massValue: 6.0,
    massExponent: 17,
    gravity: 0.0073,
    meanRadius: 5.0,
    sideralOrbit: 240.92,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Charles Kowa",
    discoveryDate: "11/09/1974",
    bodyType: "Moon",
  },
  {
    id: "thebe",
    englishName: "Thebe",
    nameDetail: "Named after the mythological nymph Thebe.",
    perihelion: 218000,
    aphelion: 226000,
    inclination: 1.08,
    massValue: 8.0,
    massExponent: 17,
    gravity: 0.02,
    meanRadius: 49.0,
    sideralOrbit: 0.6745,
    sideralRotation: 16.188,
    planet: "jupiter",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "05/03/1979",
    bodyType: "Moon",
  },
  {
    id: "adrastee",
    englishName: "Adrastea",
    nameDetail:
      "Named after the mythological Adrasteia, foster mother of the Greek god Zeus.",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.054,
    massValue: 2.0,
    massExponent: 15,
    gravity: 0.002,
    meanRadius: 8.0,
    sideralOrbit: 0.29826,
    sideralRotation: 0.7158,
    planet: "jupiter",
    discoveredBy: "David C. Jewitt, G. E. Danielson",
    discoveryDate: "08/07/1979",
    bodyType: "Moon",
  },
  {
    id: "metis",
    englishName: "Metis",
    nameDetail: "Named in 1983 after the first wife of Zeus, Metis",
    perihelion: 127974,
    aphelion: 128026,
    inclination: 0.019,
    massValue: 1.0,
    massExponent: 17,
    gravity: 0.005,
    meanRadius: 22.0,
    sideralOrbit: 0.29478,
    sideralRotation: 0.7075,
    planet: "jupiter",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "04/03/1979",
    bodyType: "Moon",
  },
  {
    id: "callirrhoe",
    englishName: "Callirrhoe",
    nameDetail:
      "Named after Callirrhoe, daughter of the river god Achelous, one of Zeus' many conquests.",
    perihelion: 0,
    aphelion: 0,
    inclination: 147.1,
    massValue: 8.7,
    massExponent: 14,
    gravity: 0.0031,
    meanRadius: 4.0,
    sideralOrbit: 758.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "J.V. Scott",
    discoveryDate: "06/10/1999",
    bodyType: "Moon",
  },
  {
    id: "themisto",
    englishName: "Themisto",
    nameDetail:
      "Named after Themisto, daughter of the river god Inachus and lover of Zeus",
    perihelion: 5909000,
    aphelion: 8874300,
    inclination: 43.08,
    massValue: 6.9,
    massExponent: 14,
    gravity: 0.0029,
    meanRadius: 4.0,
    sideralOrbit: 130.02,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy:
      "Charles Kowal 1975 - Scott S. Sheppard, David C. Jewitt 2000",
    discoveryDate: "30/09/1975",
    bodyType: "Moon",
  },
  {
    id: "megaclite",
    englishName: "Megaclite",
    nameDetail: "Named in October 2002 after Megaclite, mother by Zeus of Thebe and Locrus.",
    perihelion: 0,
    aphelion: 0,
    inclination: 152.8,
    massValue: 2.1,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 2.7,
    sideralOrbit: 752.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "taygete",
    englishName: "Taygete",
    nameDetail: "Named after Taygete, one of the Pleiades, daughter of the Titan Atlas and mother of Lacedaemon by Zeus",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.2,
    massValue: 1.6,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 2.5,
    sideralOrbit: 732.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "chaldene",
    englishName: "Chaldene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.2,
    massValue: 7.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.9,
    sideralOrbit: 723.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "harpalyke",
    englishName: "Harpalyke",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.6,
    massValue: 1.2,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 2.2,
    sideralOrbit: 623.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "kalyke",
    englishName: "Kalyke",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.2,
    massValue: 1.9,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 2.6,
    sideralOrbit: 743.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "iocaste",
    englishName: "Iocaste",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 149.4,
    massValue: 1.9,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 2.6,
    sideralOrbit: 631.5,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "erinome",
    englishName: "Erinome",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.9,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.6,
    sideralOrbit: 728.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "isonoe",
    englishName: "Isonoe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.2,
    massValue: 7.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.9,
    sideralOrbit: 725.5,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "praxidike",
    englishName: "Praxidike",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 149.0,
    massValue: 4.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.4,
    sideralOrbit: 625.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "23/11/2000",
    bodyType: "Moon",
  },
  {
    id: "autonoe",
    englishName: "Autonoe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 152.9,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0015,
    meanRadius: 2.0,
    sideralOrbit: 715.4,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "10/12/2001",
    bodyType: "Moon",
  },
  {
    id: "thyone",
    englishName: "Thyone",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.5,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0015,
    meanRadius: 2.0,
    sideralOrbit: 627.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "11/12/2001",
    bodyType: "Moon",
  },
  {
    id: "hermippe",
    englishName: "Hermippe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 150.7,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0015,
    meanRadius: 2.0,
    sideralOrbit: 633.9,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "19/12/2001",
    bodyType: "Moon",
  },
  {
    id: "aitne",
    englishName: "Aitne",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.1,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0012,
    meanRadius: 1.5,
    sideralOrbit: 730.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "19/12/2001",
    bodyType: "Moon",
  },
  {
    id: "eurydome",
    englishName: "Eurydome",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 150.3,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0012,
    meanRadius: 1.5,
    sideralOrbit: 723.9,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "19/12/2001",
    bodyType: "Moon",
  },
  {
    id: "euanthe",
    englishName: "Euanthe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.9,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0012,
    meanRadius: 1.5,
    sideralOrbit: 620.6,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "11/12/2001",
    bodyType: "Moon",
  },
  {
    id: "euporie",
    englishName: "Euporie",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.8,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 553.1,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "11/12/2001",
    bodyType: "Moon",
  },
  {
    id: "orthosie",
    englishName: "Orthosie",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.9,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.00081,
    meanRadius: 1.0,
    sideralOrbit: 622.6,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "11/12/2001",
    bodyType: "Moon",
  },
  {
    id: "sponde",
    englishName: "Sponde",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.0,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.00081,
    meanRadius: 1.0,
    sideralOrbit: 748.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "19/12/2001",
    bodyType: "Moon",
  },
  {
    id: "cale",
    englishName: "Kale",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.0,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.00081,
    meanRadius: 1.0,
    sideralOrbit: 729.5,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "19/12/2001",
    bodyType: "Moon",
  },
  {
    id: "pasithee",
    englishName: "Pasithee",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.1,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.00081,
    meanRadius: 1.0,
    sideralOrbit: 716.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "11/12/2001",
    bodyType: "Moon",
  },
  {
    id: "hegemone",
    englishName: "Hegemone",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 155.2,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 739.6,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "mneme",
    englishName: "Mneme",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.6,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 620.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "aoede",
    englishName: "Aoede",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 158.3,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 761.5,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "thelxinoe",
    englishName: "Thelxinoe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.4,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 628.1,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "arche",
    englishName: "Arche",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.0,
    massValue: 4.15,
    massExponent: 13,
    gravity: 0.0012,
    meanRadius: 1.5,
    sideralOrbit: 762.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "31/10/2002",
    bodyType: "Moon",
  },
  {
    id: "callichore",
    englishName: "Kallichore",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.5,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 764.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "helice",
    englishName: "Helike",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 154.8,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 4.0,
    sideralOrbit: 634.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "carpo",
    englishName: "Carpo",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 51.4,
    massValue: 4.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 456.1,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "eukelade",
    englishName: "Eukelade",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.5,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 4.0,
    sideralOrbit: 746.4,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "cyllene",
    englishName: "Cyllene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 149.3,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 737.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "core",
    englishName: "Kore",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.0,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 779.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "herse",
    englishName: "Herse",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.2,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 717.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j2",
    englishName: "S/2003 J 2",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.8,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 982.5,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "eupheme",
    englishName: "Eupheme",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.0,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 504.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j4",
    englishName: "S/2003 J 4",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 144.9,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 723.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "eirene",
    englishName: "Eirene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 163.1,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 759.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j9",
    englishName: "S/2003 J 9",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.5,
    massValue: 1.5,
    massExponent: 12,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 683.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j10",
    englishName: "S/2003 J 10",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.1,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 767.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j12",
    englishName: "S/2003 J 12",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.8,
    massValue: 1.0,
    massExponent: 12,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 533.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "philophrosyne",
    englishName: "Philophrosyne",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 143.6,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 668.4,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j16",
    englishName: "S/2003 J 16",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.5,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 595.4,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j18",
    englishName: "S/2003 J 18",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 146.4,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 606.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j19",
    englishName: "S/2003 J 19",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 162.9,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 701.3,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "s2003j23",
    englishName: "S/2003 J 23",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 149.2,
    massValue: 1.5,
    massExponent: 13,
    gravity: 0.00081,
    meanRadius: 1.0,
    sideralOrbit: 759.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "2003",
    bodyType: "Moon",
  },
  {
    id: "mimas",
    englishName: "Mimas",
    nameDetail: "",
    perihelion: 181770,
    aphelion: 189270,
    inclination: 1.53,
    massValue: 3.79,
    massExponent: 19,
    gravity: 0.0,
    meanRadius: 396.4,
    sideralOrbit: 0.94,
    sideralRotation: 22.56,
    planet: "saturne",
    discoveredBy: "William Herschel",
    discoveryDate: "17/09/1789",
    bodyType: "Moon",
  },
  {
    id: "encelade",
    englishName: "Enceladus",
    nameDetail: "",
    perihelion: 236830,
    aphelion: 239066,
    inclination: 0.0,
    massValue: 1.08,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 504.2,
    sideralOrbit: 1.37,
    sideralRotation: 32.88,
    planet: "saturne",
    discoveredBy: "William Herschel",
    discoveryDate: "28/08/1789",
    bodyType: "Moon",
  },
  {
    id: "tethys",
    englishName: "Tethys",
    nameDetail: "",
    perihelion: 294589,
    aphelion: 294648,
    inclination: 1.86,
    massValue: 6.18,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 1066.0,
    sideralOrbit: 1.89,
    sideralRotation: 45.312,
    planet: "saturne",
    discoveredBy: "Jean-Dominique Cassini",
    discoveryDate: "21/03/1684",
    bodyType: "Moon",
  },
  {
    id: "dione",
    englishName: "Dione",
    nameDetail: "",
    perihelion: 376580,
    aphelion: 378260,
    inclination: 0.002,
    massValue: 1.095,
    massExponent: 21,
    gravity: 0.0,
    meanRadius: 1123.4,
    sideralOrbit: 2.737,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Jean-Dominique Cassini",
    discoveryDate: "21/03/1684",
    bodyType: "Moon",
  },
  {
    id: "rhea",
    englishName: "Rhea",
    nameDetail: "",
    perihelion: 526543,
    aphelion: 527597,
    inclination: 0.35,
    massValue: 2.3,
    massExponent: 21,
    gravity: 0.0,
    meanRadius: 1528.6,
    sideralOrbit: 4.518,
    sideralRotation: 108.432,
    planet: "saturne",
    discoveredBy: "Jean-Dominique Cassini",
    discoveryDate: "23/12/1672",
    bodyType: "Moon",
  },
  {
    id: "titan",
    englishName: "Titan",
    nameDetail: "",
    perihelion: 1186680,
    aphelion: 1257060,
    inclination: 0.33,
    massValue: 1.3452,
    massExponent: 23,
    gravity: 0.0,
    meanRadius: 2575.0,
    sideralOrbit: 15.95,
    sideralRotation: 382.8,
    planet: "saturne",
    discoveredBy: "Christian Huygens",
    discoveryDate: "25/03/1655",
    bodyType: "Moon",
  },
  {
    id: "hyperion",
    englishName: "Hyperion",
    nameDetail: "",
    perihelion: 1466112,
    aphelion: 1535756,
    inclination: 0.43,
    massValue: 5.6,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 266.0,
    sideralOrbit: 21.28,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "William Cranch Bond, George Phillips Bond",
    discoveryDate: "16/09/1848",
    bodyType: "Moon",
  },
  {
    id: "japet",
    englishName: "Iapetus",
    nameDetail: "",
    perihelion: 3460068,
    aphelion: 3661612,
    inclination: 14.72,
    massValue: 1.805,
    massExponent: 21,
    gravity: 0.0,
    meanRadius: 1471.2,
    sideralOrbit: 79.33,
    sideralRotation: 1735.92,
    planet: "saturne",
    discoveredBy: "Jean-Dominique Cassini",
    discoveryDate: "25/10/1671",
    bodyType: "Moon",
  },
  {
    id: "phoebe",
    englishName: "Phoebe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 174.8,
    massValue: 8.292,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 214.4,
    sideralOrbit: 548.2,
    sideralRotation: 9.2736,
    planet: "saturne",
    discoveredBy: "William Henry Pickering",
    discoveryDate: "17/03/1899",
    bodyType: "Moon",
  },
  {
    id: "janus",
    englishName: "Janus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.14,
    massValue: 1.9,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 89.5,
    sideralOrbit: 0.7,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Audouin Dollfus",
    discoveryDate: "15/12/1966",
    bodyType: "Moon",
  },
  {
    id: "epimethee",
    englishName: "Epimetheus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.34,
    massValue: 5.3,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 113.4,
    sideralOrbit: 0.69,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Richard L. Walker",
    discoveryDate: "18/12/1966",
    bodyType: "Moon",
  },
  {
    id: "helene",
    englishName: "Helene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.199,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 17.6,
    sideralOrbit: 2.736,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Pierre Laques, Raymond Despiau, Jean Lecacheux",
    discoveryDate: "01/03/1980",
    bodyType: "Moon",
  },
  {
    id: "telesto",
    englishName: "Telesto",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 1.158,
    massValue: 1.0,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 12.4,
    sideralOrbit: 1.89,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Bradford A. Smith, Harold J. Reitsema, Stephen M. Larson, John W. Fountain",
    discoveryDate: "08/04/1980",
    bodyType: "Moon",
  },
  {
    id: "calypso",
    englishName: "Calypso",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 1.473,
    massValue: 6.5,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 10.7,
    sideralOrbit: 1.89,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Dan Pascu, P. Kenneth Seidelmann, William A. Baum, Douglas Currie",
    discoveryDate: "13/03/1980",
    bodyType: "Moon",
  },
  {
    id: "atlas",
    englishName: "Atlas",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.3,
    massValue: 7.0,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 15.1,
    sideralOrbit: 0.602,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Richard J. Terrile",
    discoveryDate: "12/11/1980",
    bodyType: "Moon",
  },
  {
    id: "promethee",
    englishName: "Prometheus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 1.6,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 43.1,
    sideralOrbit: 0.613,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Stewart A. Collins, D. Carlson",
    discoveryDate: "??/10/1980",
    bodyType: "Moon",
  },
  {
    id: "pandore",
    englishName: "Pandora",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 1.4,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 40.7,
    sideralOrbit: 0.629,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Stewart A. Collins",
    discoveryDate: "??/10/1980",
    bodyType: "Moon",
  },
  {
    id: "pan",
    englishName: "Pan",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 4.95,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 14.1,
    sideralOrbit: 0.575,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Mark R. Showalter",
    discoveryDate: "22/08/1981",
    bodyType: "Moon",
  },
  {
    id: "ymir",
    englishName: "Ymir",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 167.9,
    massValue: 3.97,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 9.0,
    sideralOrbit: 1315.4,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Brett J. Gladman",
    discoveryDate: "07/08/2000",
    bodyType: "Moon",
  },
  {
    id: "paaliaq",
    englishName: "Paaliaq",
    nameDetail: "",
    perihelion: 6908035,
    aphelion: 23139965,
    inclination: 47.2,
    massValue: 7.25,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 10.0,
    sideralOrbit: 686.9,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "07/08/2000",
    bodyType: "Moon",
  },
  {
    id: "tarvos",
    englishName: "Tarvos",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 33.8,
    massValue: 2.3,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 7.0,
    sideralOrbit: 926.2,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "ijiraq",
    englishName: "Ijiraq",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 49.1,
    massValue: 1.18,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 5.0,
    sideralOrbit: 451.4,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "suttungr",
    englishName: "Suttungr",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 175.8,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1016.7,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "kiviuq",
    englishName: "Kiviuq",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 48.7,
    massValue: 2.79,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 7.0,
    sideralOrbit: 449.2,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Brett J. Gladman",
    discoveryDate: "07/08/2000",
    bodyType: "Moon",
  },
  {
    id: "mundilfari",
    englishName: "Mundilfari",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 169.4,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 952.6,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "albiorix",
    englishName: "Albiorix",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 34.0,
    massValue: 2.23,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 13.0,
    sideralOrbit: 783.5,
    sideralRotation: 13.32,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "09/11/2000",
    bodyType: "Moon",
  },
  {
    id: "skathi",
    englishName: "Skathi",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.5,
    massValue: 3.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 728.2,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "erriapo",
    englishName: "Erriapus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 34.6,
    massValue: 6.8,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 4.0,
    sideralOrbit: 871.2,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "siarnaq",
    englishName: "Siarnaq",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 45.6,
    massValue: 4.35,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 16.0,
    sideralOrbit: 895.6,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "thrymr",
    englishName: "Thrymr",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 175.0,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1094.3,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "John J. Kavelaars, Brett J. Gladman",
    discoveryDate: "23/09/2000",
    bodyType: "Moon",
  },
  {
    id: "narvi",
    englishName: "Narvi",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.8,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1003.9,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt, Jan Kleyna",
    discoveryDate: "05/02/2003",
    bodyType: "Moon",
  },
  {
    id: "methone",
    englishName: "Methone",
    nameDetail: "",
    perihelion: 194421,
    aphelion: 194459,
    inclination: 0.0,
    massValue: 2.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 1.6,
    sideralOrbit: 1.01,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco, Sébastien Charnoz",
    discoveryDate: "01/06/2004",
    bodyType: "Moon",
  },
  {
    id: "pallene",
    englishName: "Pallene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 6.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.5,
    sideralOrbit: 1.14,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco, Sébastien Charnoz",
    discoveryDate: "01/06/2004",
    bodyType: "Moon",
  },
  {
    id: "pollux",
    englishName: "Polydeuces",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.1705,
    massValue: 1.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 2.737,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco",
    discoveryDate: "21/10/2004",
    bodyType: "Moon",
  },
  {
    id: "daphnis",
    englishName: "Daphnis",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 1.0,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.8,
    sideralOrbit: 0.594,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco",
    discoveryDate: "01/05/2009",
    bodyType: "Moon",
  },
  {
    id: "aegir",
    englishName: "Aegir",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 166.7,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1116.5,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "bebhionn",
    englishName: "Bebhionn",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 35.0,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 834.8,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "bergelmir",
    englishName: "Bergelmir",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 158.5,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1005.9,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "bestla",
    englishName: "Bestla",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 145.2,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1083.6,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "13/12/2004",
    bodyType: "Moon",
  },
  {
    id: "farbauti",
    englishName: "Farbauti",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 156.4,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1086.1,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "fenrir",
    englishName: "Fenrir",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.9,
    massValue: 5.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 1260.3,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "13/12/2004",
    bodyType: "Moon",
  },
  {
    id: "fornjot",
    englishName: "Fornjot",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 170.4,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1490.9,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "hati",
    englishName: "Hati",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.8,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1038.7,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "hyrrokkin",
    englishName: "Hyrrokkin",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.4,
    massValue: 3.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 4.0,
    sideralOrbit: 931.8,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "kari",
    englishName: "Kari",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 156.3,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1233.6,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "loge",
    englishName: "Loge",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 173.1,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1312.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "13/12/2004",
    bodyType: "Moon",
  },
  {
    id: "skoll",
    englishName: "Skoll",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 161.2,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 878.3,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "surtur",
    englishName: "Surtur",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 177.5,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1297.7,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "anthe",
    englishName: "Anthe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.1,
    massValue: 5.0,
    massExponent: 12,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 1.04,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco, l'équipe Cassini",
    discoveryDate: "30/05/2007",
    bodyType: "Moon",
  },
  {
    id: "jarnsaxa",
    englishName: "Jarnsaxa",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 163.3,
    massValue: 1.0,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 964.7,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "05/01/2006",
    bodyType: "Moon",
  },
  {
    id: "greip",
    englishName: "Greip",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 179.8,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 921.2,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "05/01/2006",
    bodyType: "Moon",
  },
  {
    id: "tarqeq",
    englishName: "Tarqeq",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 46.1,
    massValue: 2.3,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 887.5,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "05/01/2006",
    bodyType: "Moon",
  },
  {
    id: "egeon",
    englishName: "Aegaeon",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.001,
    massValue: 1.0,
    massExponent: 11,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 0.808,
    sideralRotation: 19.63,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco",
    discoveryDate: "15/08/2008",
    bodyType: "Moon",
  },
  {
    id: "s2004s7",
    englishName: "S/2004 S 7",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.1,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1103.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s12",
    englishName: "S/2004 S 12",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.0,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1048.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s13",
    englishName: "S/2004 S 13",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 167.4,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 906.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "12/12/2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s17",
    englishName: "S/2004 S 17",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 166.6,
    massValue: 5.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 986.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "13/12/2004",
    bodyType: "Moon",
  },
  {
    id: "s2006s1",
    englishName: "S/2006 S 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 154.2,
    massValue: 1.0,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 970.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "04/01/2006",
    bodyType: "Moon",
  },
  {
    id: "s2006s3",
    englishName: "S/2006 S 3",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 150.8,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1142.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "05/01/2006",
    bodyType: "Moon",
  },
  {
    id: "s2007s2",
    englishName: "S/2007 S 2",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 176.7,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 800.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "01/05/2007",
    bodyType: "Moon",
  },
  {
    id: "s2007s3",
    englishName: "S/2007 S 3",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 177.2,
    massValue: 1.5,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 3.0,
    sideralOrbit: 1100.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy:
      "Scott S. Sheppard, David C. Jewitt, Jan Kleyna, Brian G. Marsden",
    discoveryDate: "01/05/2007",
    bodyType: "Moon",
  },
  {
    id: "s2009s1",
    englishName: "S/2009 S 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 1.0,
    massExponent: 11,
    gravity: 0.0,
    meanRadius: 0.3,
    sideralOrbit: 0.4715,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco",
    discoveryDate: "26/07/2009",
    bodyType: "Moon",
  },
  {
    id: "ariel",
    englishName: "Ariel",
    nameDetail: "",
    perihelion: 190670,
    aphelion: 191130,
    inclination: 0.04,
    massValue: 12.9,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 581.1,
    sideralOrbit: 2.52038,
    sideralRotation: 60.4891,
    planet: "uranus",
    discoveredBy: "William Lassell",
    discoveryDate: "24/10/1851",
    bodyType: "Moon",
  },
  {
    id: "umbriel",
    englishName: "Umbriel",
    nameDetail: "",
    perihelion: 265100,
    aphelion: 267500,
    inclination: 0.13,
    massValue: 12.2,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 584.7,
    sideralOrbit: 4.14418,
    sideralRotation: 99.499,
    planet: "uranus",
    discoveredBy: "William Lassell",
    discoveryDate: "24/10/1851",
    bodyType: "Moon",
  },
  {
    id: "titania",
    englishName: "Titania",
    nameDetail: "",
    perihelion: 435800,
    aphelion: 436800,
    inclination: 0.08,
    massValue: 34.2,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 788.9,
    sideralOrbit: 8.70587,
    sideralRotation: 208.9408,
    planet: "uranus",
    discoveredBy: "William Herschel",
    discoveryDate: "11/01/1787",
    bodyType: "Moon",
  },
  {
    id: "oberon",
    englishName: "Oberon",
    nameDetail: "",
    perihelion: 582702,
    aphelion: 584336,
    inclination: 0.07,
    massValue: 28.8,
    massExponent: 20,
    gravity: 0.0,
    meanRadius: 761.4,
    sideralOrbit: 13.46323,
    sideralRotation: 323.1176,
    planet: "uranus",
    discoveredBy: "William Herschel",
    discoveryDate: "11/01/1787",
    bodyType: "Moon",
  },
  {
    id: "miranda",
    englishName: "Miranda",
    nameDetail: "",
    perihelion: 129703,
    aphelion: 130041,
    inclination: 4.34,
    massValue: 6.6,
    massExponent: 19,
    gravity: 0.0,
    meanRadius: 240.0,
    sideralOrbit: 1.41348,
    sideralRotation: 33.9235,
    planet: "uranus",
    discoveredBy: "Gerard Kuiper",
    discoveryDate: "16/02/1948",
    bodyType: "Moon",
  },
  {
    id: "cordelia",
    englishName: "Cordelia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.08,
    massValue: 4.5,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 20.0,
    sideralOrbit: 0.33503,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Richard J. Terrile",
    discoveryDate: "20/01/1986",
    bodyType: "Moon",
  },
  {
    id: "ophelia",
    englishName: "Ophelia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.1,
    massValue: 5.4,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 21.0,
    sideralOrbit: 0.3764,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Richard J. Terrile",
    discoveryDate: "20/01/1986",
    bodyType: "Moon",
  },
  {
    id: "bianca",
    englishName: "Bianca",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.19,
    massValue: 9.2,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 27.0,
    sideralOrbit: 0.43458,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Bradford A. Smith",
    discoveryDate: "23/01/1986",
    bodyType: "Moon",
  },
  {
    id: "cressida",
    englishName: "Cressida",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.01,
    massValue: 3.4,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 41.0,
    sideralOrbit: 0.46357,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "09/01/1986",
    bodyType: "Moon",
  },
  {
    id: "desdemona",
    englishName: "Desdemona",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.11,
    massValue: 1.8,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 35.0,
    sideralOrbit: 0.47365,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "13/01/1986",
    bodyType: "Moon",
  },
  {
    id: "juliet",
    englishName: "Juliet",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.07,
    massValue: 5.6,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 53.0,
    sideralOrbit: 0.49307,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "03/01/1986",
    bodyType: "Moon",
  },
  {
    id: "portia",
    englishName: "Portia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.06,
    massValue: 1.7,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 70.0,
    sideralOrbit: 0.5132,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "03/01/1986",
    bodyType: "Moon",
  },
  {
    id: "rosalind",
    englishName: "Rosalind",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.28,
    massValue: 0.25,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 36.0,
    sideralOrbit: 0.55846,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "13/01/1986",
    bodyType: "Moon",
  },
  {
    id: "belinda",
    englishName: "Belinda",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.03,
    massValue: 4.9,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 45.0,
    sideralOrbit: 0.62353,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "13/01/1986",
    bodyType: "Moon",
  },
  {
    id: "puck",
    englishName: "Puck",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.32,
    massValue: 2.9,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 81.0,
    sideralOrbit: 0.76183,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "30/12/1985",
    bodyType: "Moon",
  },
  {
    id: "caliban",
    englishName: "Caliban",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 141.53,
    massValue: 2.5,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 36.0,
    sideralOrbit: -579.5,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Brett J. Gladman, Philip D. Nicholson, Joseph A. Burns, John J. Kavelaars",
    discoveryDate: "06/09/1997",
    bodyType: "Moon",
  },
  {
    id: "sycorax",
    englishName: "Sycorax",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 159.42,
    massValue: 2.3,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 75.0,
    sideralOrbit: -1283.4,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Philip D. Nicholson, Brett J. Gladman, Joseph A. Burns, John J. Kavelaars",
    discoveryDate: "06/09/1997",
    bodyType: "Moon",
  },
  {
    id: "prospero",
    englishName: "Prospero",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 151.83,
    massValue: 8.5,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 25.0,
    sideralOrbit: -1977.3,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Brett J. Gladman, Jean-Marc Petit, Hans Scholl",
    discoveryDate: "18/07/1999",
    bodyType: "Moon",
  },
  {
    id: "setebos",
    englishName: "Setebos",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 158.24,
    massValue: 7.5,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 24.0,
    sideralOrbit: -2234.8,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "John J. Kavelaars, Brett J. Gladman, Matthew J. Holman, Jean-Marc Petit, Hans Scholl",
    discoveryDate: "18/07/1999",
    bodyType: "Moon",
  },
  {
    id: "stephano",
    englishName: "Stephano",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 143.82,
    massValue: 2.2,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 16.0,
    sideralOrbit: -676.5,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Brett J. Gladman, Matthew J. Holman, John J. Kavelaars, Jean-Marc Petit, Hans Scholl",
    discoveryDate: "18/07/1999",
    bodyType: "Moon",
  },
  {
    id: "trinculo",
    englishName: "Trinculo",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 166.93,
    massValue: 3.9,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 9.0,
    sideralOrbit: -758.1,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic",
    discoveryDate: "13/08/2001",
    bodyType: "Moon",
  },
  {
    id: "francisco",
    englishName: "Francisco",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 147.25,
    massValue: 7.2,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 11.0,
    sideralOrbit: -266.6,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic, Brett J. Gladman",
    discoveryDate: "13/08/2001",
    bodyType: "Moon",
  },
  {
    id: "margaret",
    englishName: "Margaret",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 57.37,
    massValue: 5.4,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 10.0,
    sideralOrbit: 1694.8,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "29/08/2003",
    bodyType: "Moon",
  },
  {
    id: "ferdinand",
    englishName: "Ferdinand",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 169.79,
    massValue: 5.4,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 10.0,
    sideralOrbit: -2823.4,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Dan Milisavljevic, Brett J. Gladman",
    discoveryDate: "13/08/2001",
    bodyType: "Moon",
  },
  {
    id: "perdita",
    englishName: "Perdita",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.47,
    massValue: 1.8,
    massExponent: 19,
    gravity: 0.0,
    meanRadius: 13.0,
    sideralOrbit: 0.638,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Erich Karkoschka",
    discoveryDate: "18/01/1986",
    bodyType: "Moon",
  },
  {
    id: "mab",
    englishName: "Mab",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.13,
    massValue: 1.0,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 12.0,
    sideralOrbit: 0.923,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Mark R. Showalter, Jack J. Lissauer",
    discoveryDate: "25/08/2003",
    bodyType: "Moon",
  },
  {
    id: "cupid",
    englishName: "Cupid",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.1,
    massValue: 3.8,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 9.0,
    sideralOrbit: 0.613,
    sideralRotation: 0.0,
    planet: "uranus",
    discoveredBy: "Mark R. Showalter, Jack J. Lissauer",
    discoveryDate: "25/08/2003",
    bodyType: "Moon",
  },
  {
    id: "triton",
    englishName: "Triton",
    nameDetail: "",
    perihelion: 354753,
    aphelion: 354765,
    inclination: 157.345,
    massValue: 2.14,
    massExponent: 22,
    gravity: 0.78,
    meanRadius: 1353.4,
    sideralOrbit: 5.87685,
    sideralRotation: 141.0444,
    planet: "neptune",
    discoveredBy: "William Lassell",
    discoveryDate: "10/10/1846",
    bodyType: "Moon",
  },
  {
    id: "nereide",
    englishName: "Nereid",
    nameDetail: "",
    perihelion: 1372000,
    aphelion: 9655000,
    inclination: 7.23,
    massValue: 3.0,
    massExponent: 19,
    gravity: 0.071,
    meanRadius: 170.0,
    sideralOrbit: 360.13619,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Gerard Kuiper",
    discoveryDate: "01/05/1949",
    bodyType: "Moon",
  },
  {
    id: "naiade",
    englishName: "Naiad",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 4.74,
    massValue: 2.0,
    massExponent: 17,
    gravity: 0.01,
    meanRadius: 33.0,
    sideralOrbit: 0.2944,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Richard J. Terrile",
    discoveryDate: "18/09/1989",
    bodyType: "Moon",
  },
  {
    id: "thalassa",
    englishName: "Thalassa",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.21,
    massValue: 4.0,
    massExponent: 17,
    gravity: 0.013,
    meanRadius: 41.0,
    sideralOrbit: 0.31149,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Richard J. Terrile",
    discoveryDate: "18/09/1989",
    bodyType: "Moon",
  },
  {
    id: "despina",
    englishName: "Despina",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.07,
    massValue: 2.0,
    massExponent: 18,
    gravity: 0.023,
    meanRadius: 75.0,
    sideralOrbit: 0.33466,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "28/07/1989",
    bodyType: "Moon",
  },
  {
    id: "galatee",
    englishName: "Galatea",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.05,
    massValue: 2.0,
    massExponent: 18,
    gravity: 0.03,
    meanRadius: 88.0,
    sideralOrbit: 0.42875,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Stephen P. Synnott",
    discoveryDate: "28/07/1989",
    bodyType: "Moon",
  },
  {
    id: "larissa",
    englishName: "Larissa",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.2,
    massValue: 5.0,
    massExponent: 18,
    gravity: 0.034,
    meanRadius: 97.0,
    sideralOrbit: 0.55465,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy:
      "Harold J. Reitsema, William B. Hubbard, Larry A. Lebofsky, David J. Tholen",
    discoveryDate: "24/05/1981",
    bodyType: "Moon",
  },
  {
    id: "protee",
    englishName: "Proteus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.04,
    massValue: 5.0,
    massExponent: 19,
    gravity: 0.075,
    meanRadius: 210.0,
    sideralOrbit: 1.12232,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Stephen P. Synnott, Bradford A. Smith",
    discoveryDate: "16/06/1989",
    bodyType: "Moon",
  },
  {
    id: "halimede",
    englishName: "Halimede",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 134.1,
    massValue: 2.0,
    massExponent: 17,
    gravity: 0.01,
    meanRadius: 30.0,
    sideralOrbit: 1879.7,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, Dan Milisavljevic",
    discoveryDate: "14/08/2002",
    bodyType: "Moon",
  },
  {
    id: "psamathee",
    englishName: "Psamathe",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 137.4,
    massValue: 2.0,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 20.0,
    sideralOrbit: 9115.9,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Scott S. Sheppard",
    discoveryDate: "19/08/2003",
    bodyType: "Moon",
  },
  {
    id: "sao",
    englishName: "Sao",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 48.5,
    massValue: 1.0,
    massExponent: 17,
    gravity: 0.01,
    meanRadius: 20.0,
    sideralOrbit: 2914.1,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, Dan Milisavljevic",
    discoveryDate: "14/08/2002",
    bodyType: "Moon",
  },
  {
    id: "laomedie",
    englishName: "Laomedeia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 34.7,
    massValue: 1.0,
    massExponent: 17,
    gravity: 0.01,
    meanRadius: 20.0,
    sideralOrbit: 3167.9,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy:
      "Matthew J. Holman, John J. Kavelaars, Tommy Grav, Wesley C. Fraser, Dan Milisavljevic",
    discoveryDate: "13/08/2002",
    bodyType: "Moon",
  },
  {
    id: "neso",
    englishName: "Neso",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 132.6,
    massValue: 1.0,
    massExponent: 17,
    gravity: 0.0,
    meanRadius: 30.0,
    sideralOrbit: 9374.0,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Matthew J. Holman",
    discoveryDate: "14/08/2002",
    bodyType: "Moon",
  },
  {
    id: "charon",
    englishName: "Charon",
    nameDetail: "",
    perihelion: 19587,
    aphelion: 19595,
    inclination: 0.08,
    massValue: 1.58,
    massExponent: 21,
    gravity: 0.0,
    meanRadius: 606.0,
    sideralOrbit: 6.387,
    sideralRotation: 0.0,
    planet: "pluton",
    discoveredBy: "James W. Christy",
    discoveryDate: "13/04/1978",
    bodyType: "Moon",
  },
  {
    id: "nix",
    englishName: "Nix",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.133,
    massValue: 4.5,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 44.0,
    sideralOrbit: 24.854,
    sideralRotation: 0.0,
    planet: "pluton",
    discoveredBy: "Hubble Space Telescope Pluto Companion Search Team",
    discoveryDate: "15/05/2005",
    bodyType: "Moon",
  },
  {
    id: "hydra",
    englishName: "Hydra",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.242,
    massValue: 4.8,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 36.0,
    sideralOrbit: 38.2,
    sideralRotation: 0.0,
    planet: "pluton",
    discoveredBy: "Hubble Space Telescope Pluto Companion Search Team",
    discoveryDate: "15/05/2005",
    bodyType: "Moon",
  },
  {
    id: "namaka",
    englishName: "Namaka",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 113.0,
    massValue: 1.79,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 85.0,
    sideralOrbit: 18.27,
    sideralRotation: 0.0,
    planet: "haumea",
    discoveredBy: "Michael E. Brown",
    discoveryDate: "30/06/2005",
    bodyType: "Moon",
  },
  {
    id: "hiiaka",
    englishName: "Hiʻiaka",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 126.35,
    massValue: 1.78,
    massExponent: 19,
    gravity: 0.0,
    meanRadius: 160.0,
    sideralOrbit: 49.12,
    sideralRotation: 0.0,
    planet: "haumea",
    discoveredBy: "Michael E. Brown",
    discoveryDate: "26/01/2005",
    bodyType: "Moon",
  },
  {
    id: "dysnomie",
    englishName: "Dysnomia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 45.49,
    massValue: 145.0,
    massExponent: 18,
    gravity: 0.0,
    meanRadius: 350.0,
    sideralOrbit: 15.785,
    sideralRotation: 0.0,
    planet: "eris",
    discoveredBy: "Michael E. Brown",
    discoveryDate: "??/09/2005",
    bodyType: "Moon",
  },
  {
    id: "dia",
    englishName: "Dia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 28.23,
    massValue: 9.0,
    massExponent: 13,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 287.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard, David C. Jewitt",
    discoveryDate: "27/12/2000",
    bodyType: "Moon",
  },
  {
    id: "s2004s3",
    englishName: "S/2004 S 3",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.62,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carl Murray",
    discoveryDate: "21/06/2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s4",
    englishName: "S/2004 S 4",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.61,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carl Murray",
    discoveryDate: "09/09/2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s6",
    englishName: "S/2004 S 6",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.02,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.5,
    sideralOrbit: 0.61,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "Carolyn C. Porco",
    discoveryDate: "28/10/2004",
    bodyType: "Moon",
  },
  {
    id: "s2010j1",
    englishName: "S/2010 J 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 163.2,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 723.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Jacobson, Brozovic, Gladman, Alexandersen",
    discoveryDate: "07/09/2010",
    bodyType: "Moon",
  },
  {
    id: "s2010j2",
    englishName: "S/2010 J 2",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 150.4,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 588.1,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Christian Veillet",
    discoveryDate: "08/09/2010",
    bodyType: "Moon",
  },
  {
    id: "petitprince",
    englishName: "The Little Prince",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 8.0,
    massValue: 1.2,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 13.0,
    sideralOrbit: 4.76,
    sideralRotation: 0.0,
    planet: "eugenia",
    discoveredBy:
      "W. J. Merline, L. M. Close, C. Dumas, C. R. Chapman, F. Roddier, F. Menard, D. C. Slater, G. Duvert, J. C. Shelton, T. Morgan",
    discoveryDate: "01/11/1999",
    bodyType: "Moon",
  },
  {
    id: "remus",
    englishName: "Remus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 2.0,
    massValue: 2.0,
    massExponent: 14,
    gravity: 0.0,
    meanRadius: 7.0,
    sideralOrbit: 1.37,
    sideralRotation: 0.0,
    planet: "sylvia",
    discoveredBy:
      "Franck Marchis, Pascal Descamps, Daniel Hestroffer, Jérome Berthier",
    discoveryDate: "09/08/2005",
    bodyType: "Moon",
  },
  {
    id: "vanth",
    englishName: "Vanth",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 105.03,
    massValue: 3.6,
    massExponent: 19,
    gravity: 0.0,
    meanRadius: 434.0,
    sideralOrbit: 9.539,
    sideralRotation: 0.0,
    planet: "orcus",
    discoveredBy: "Michael E. Brown, T.A. Suer",
    discoveryDate: "13/11/2005",
    bodyType: "Moon",
  },
  {
    id: "dactyl",
    englishName: "(243) Ida I Dactyl",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 8.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.0,
    sideralOrbit: 1.54,
    sideralRotation: 0.0,
    planet: "ida",
    discoveredBy: "Ann Harch",
    discoveryDate: "17/02/1994",
    bodyType: "Moon",
  },
  {
    id: "romulus",
    englishName: "Romulus",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 1.7,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 10.8,
    sideralOrbit: 3.6496,
    sideralRotation: 0.0,
    planet: "sylvia",
    discoveredBy: "Michael E. Brown, Jean-Luc Margot",
    discoveryDate: "18/02/2001",
    bodyType: "Moon",
  },
  {
    id: "alexhelios",
    englishName: "Alexhelios",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 6.9,
    sideralOrbit: 2.3,
    sideralRotation: 0.0,
    planet: "kleopatra",
    discoveredBy:
      "F. Marchis, P. Descamps, J. Berthier, F. Vachier, J. P. Emery",
    discoveryDate: "18/09/2008",
    bodyType: "Moon",
  },
  {
    id: "cleoselene",
    englishName: "Cleoselene",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 8.9,
    sideralOrbit: 1.8,
    sideralRotation: 0.0,
    planet: "kleopatra",
    discoveredBy:
      "F. Marchis, P. Descamps, J. Berthier, F. Vachier, J. P. Emery",
    discoveryDate: "18/09/2008",
    bodyType: "Moon",
  },
  {
    id: "weywot",
    englishName: "Weywot",
    nameDetail: "",
    perihelion: 12470,
    aphelion: 16530,
    inclination: 14.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 170.0,
    sideralOrbit: 12.438,
    sideralRotation: 0.0,
    planet: "quaoar",
    discoveredBy: "Michael E. Brown, T.A. Suer",
    discoveryDate: "22/02/2007",
    bodyType: "Moon",
  },
  {
    id: "kerberos",
    englishName: "Kerberos",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.389,
    massValue: 1.64,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 25.0,
    sideralOrbit: 32.167,
    sideralRotation: 0.0,
    planet: "pluton",
    discoveredBy: "Télescope spatial Hubble - Pluto Companion Search Team",
    discoveryDate: "20/07/2011",
    bodyType: "Moon",
  },
  {
    id: "s2011j1",
    englishName: "S/2011 J 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 162.8,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 580.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard",
    discoveryDate: "29/01/2012",
    bodyType: "Moon",
  },
  {
    id: "s2011j2",
    englishName: "S/2011 J 2",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 148.8,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 726.8,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard",
    discoveryDate: "29/01/2012",
    bodyType: "Moon",
  },
  {
    id: "styx",
    englishName: "Styx",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.809,
    massValue: 7.5,
    massExponent: 15,
    gravity: 0.0,
    meanRadius: 20.0,
    sideralOrbit: 20.16,
    sideralRotation: 0.0,
    planet: "pluton",
    discoveredBy:
      "Télescope spatial Hubble - Pluto Companion Search Team - Mark Showalter",
    discoveryDate: "11/07/2012",
    bodyType: "Moon",
  },
  {
    id: "hippocampe",
    englishName: "Hippocamp",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    massValue: 3.0,
    massExponent: 16,
    gravity: 0.0,
    meanRadius: 17.0,
    sideralOrbit: 0.95,
    sideralRotation: 0.0,
    planet: "neptune",
    discoveredBy: "Mark Showalter",
    discoveryDate: "01/07/2013",
    bodyType: "Moon",
  },
  {
    id: "mk2",
    englishName: "S/2015 (136472) 1",
    nameDetail: "",
    perihelion: 21100,
    aphelion: 300000,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 75.0,
    sideralOrbit: 12.4,
    sideralRotation: 0.0,
    planet: "makemake",
    discoveredBy: "Alex H. Parker, Marc W. Buie, M. Grundy, Keith S. Noll",
    discoveryDate: "26/04/2016",
    bodyType: "Moon",
  },
  {
    id: "s2017j1",
    englishName: "S/2017 J 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 149.2,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 734.2,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "06/06/2017",
    bodyType: "Moon",
  },
  {
    id: "s2016j1",
    englishName: "S/2016 J 1",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 139.8,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 602.7,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "06/06/2017",
    bodyType: "Moon",
  },
  {
    id: "valetudo",
    englishName: "Valetudo",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 34.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 533.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j2",
    englishName: "S/2017 J 2",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 166.4,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 723.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j3",
    englishName: "S/2017 J 3",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 147.9,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 606.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "pandia",
    englishName: "Pandia",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 28.2,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 252.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j5",
    englishName: "S/2017 J 5",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.3,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 719.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j6",
    englishName: "S/2017 J 6",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 155.2,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 683.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j7",
    englishName: "S/2017 J 7",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 143.4,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 603.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j8",
    englishName: "S/2017 J 8",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.7,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.5,
    sideralOrbit: 720.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2017j9",
    englishName: "S/2017 J 9",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 152.7,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 639.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "ersa",
    englishName: "Ersa",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 30.6,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 252.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott Sheppard",
    discoveryDate: "17/07/2018",
    bodyType: "Moon",
  },
  {
    id: "s2004s22",
    englishName: "S/2004 S 22",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 177.4,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s21",
    englishName: "S/2004 S 21",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 154.6,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s20",
    englishName: "S/2004 S 20",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 163.1,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s23",
    englishName: "S/2004 S 23",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 177.7,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s24",
    englishName: "S/2004 S 24",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 36.78,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 1317.6,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s25",
    englishName: "S/2004 S 25",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 173.3,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s26",
    englishName: "S/2004 S 26",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 171.3,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s27",
    englishName: "S/2004 S 27",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 167.1,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s28",
    englishName: "S/2004 S 28",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 171.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s29",
    englishName: "S/2004 S 29",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 44.43,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 858.77,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s30",
    englishName: "S/2004 S 30",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 156.3,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s31",
    englishName: "S/2004 S 31",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 48.11,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 853.8,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s32",
    englishName: "S/2004 S 32",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 158.5,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s33",
    englishName: "S/2004 S 33",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 161.5,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s34",
    englishName: "S/2004 S 34",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 165.7,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s35",
    englishName: "S/2004 S 35",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 176.4,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s36",
    englishName: "S/2004 S 36",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 147.6,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.5,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s37",
    englishName: "S/2004 S 37",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 164.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s38",
    englishName: "S/2004 S 38",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 155.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 2.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2004s39",
    englishName: "S/2004 S 39",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 167.6,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 1.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "saturne",
    discoveredBy: "S. Sheppard, D. Jewitt, J. Kleyna",
    discoveryDate: "2004",
    bodyType: "Moon",
  },
  {
    id: "s2003j24",
    englishName: "S/2003 J 24",
    nameDetail: "",
    perihelion: 0,
    aphelion: 0,
    inclination: 0.0,
    mass: null,
    massExponent: null,
    gravity: 0.0,
    meanRadius: 0.0,
    sideralOrbit: 0.0,
    sideralRotation: 0.0,
    planet: "jupiter",
    discoveredBy: "Scott S. Sheppard",
    discoveryDate: "05/02/2003",
    bodyType: "Moon",
  },
];

let filtered = moonData.filter((moon) => {
  return moon.discoveredBy === "Scott S. Sheppard";
});

console.log(filtered);
